name: Auto Merge to Master

on:
  push:
    branches:
      - xfbajka

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "Flaaviu96"
          git config user.email "flaviu.raul96@gmail.com"

      - name: Merge to master
        run: |
          git checkout master
          git pull origin master
          git merge xfbajka
          git push origin master
